const ACTIONS = {
  ENTER_CHARACTER: "ENTER_NUMBER",
  CALCULATE_EXPRESSION: "CALCULATE_EXPRESSION",
  DELETE_CHARACTER: "DELETE_CHARACTER",
  CLEAR_CALCULATION: "CLEAR_CALCULATION",
};

const BUTTON_KEY_VALUES = {
  1: ACTIONS.ENTER_CHARACTER,
  2: ACTIONS.ENTER_CHARACTER,
  3: ACTIONS.ENTER_CHARACTER,
  4: ACTIONS.ENTER_CHARACTER,
  5: ACTIONS.ENTER_CHARACTER,
  6: ACTIONS.ENTER_CHARACTER,
  7: ACTIONS.ENTER_CHARACTER,
  8: ACTIONS.ENTER_CHARACTER,
  9: ACTIONS.ENTER_CHARACTER,
  0: ACTIONS.ENTER_CHARACTER,
  ".": ACTIONS.ENTER_CHARACTER,
  "(": ACTIONS.ENTER_CHARACTER,
  ")": ACTIONS.ENTER_CHARACTER,
  "+": ACTIONS.ENTER_CHARACTER,
  "-": ACTIONS.ENTER_CHARACTER,
  "*": ACTIONS.ENTER_CHARACTER,
  "/": ACTIONS.ENTER_CHARACTER,
  "=": ACTIONS.CALCULATE_EXPRESSION,
  "←": ACTIONS.DELETE_CHARACTER,
  CE: ACTIONS.CLEAR_CALCULATION,
};

export { ACTIONS, BUTTON_KEY_VALUES };
